### ISSUE TITLE
Error with the file 9_asyncFunctions.ts

### ISSUE THREAD

**Issue by mohamedmehdigara** [katiewoolston/typescript-workshop-exercises#5]

**Comment by katiewoolston** [comment]
Good pickup! It looks like TypeScript is now requiring the Promise type to be explicit. I've pushed a fix for this.

Thanks!

**Comment by katiewoolston** [comment]
Good pickup! It looks like TypeScript is now requiring the Promise type to be explicit. I've pushed a fix for this.

Thanks!
